name: nodecast_tv_android
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.1
  webview_flutter_android: ^4.10.11
  webview_flutter_platform_interface: ^2.14.0
  flutter_inappwebview: ^6.2.0-beta.3
  http: ^1.6.0
  shared_preferences: ^2.5.4
  custom_tv_text_field: ^1.0.8
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
